/**
 * Generate dialect-specific Prisma schema files from prisma/models.prisma.
 *
 * Usage: npx tsx scripts/generate-schema.ts
 *
 * Output:
 *   prisma/generated/mysql.prisma
 *   prisma/generated/postgresql.prisma
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const MODELS_PATH = path.join(ROOT, 'prisma', 'models.prisma');
const OUTPUT_DIR = path.join(ROOT, 'prisma', 'generated');

interface DialectConfig {
  provider: string;
  envVar: string;
}

const dialects: Record<string, DialectConfig> = {
  mysql: { provider: 'mysql', envVar: 'MYSQL_URL' },
  postgresql: { provider: 'postgresql', envVar: 'POSTGRES_URL' },
};

const models = fs.readFileSync(MODELS_PATH, 'utf-8');

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

for (const [name, config] of Object.entries(dialects)) {
  const schema = `// Auto-generated by scripts/generate-schema.ts — do not edit manually.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${config.provider}"
  url      = env("${config.envVar}")
}

${models}
`;

  const outPath = path.join(OUTPUT_DIR, `${name}.prisma`);
  fs.writeFileSync(outPath, schema, 'utf-8');
  console.log(`Generated ${path.relative(ROOT, outPath)}`);
}
