/**
 * Generate prisma/schema.prisma (generator + datasource only) for a given dialect.
 *
 * Models live in prisma/models.prisma and are combined automatically via
 * Prisma's multi-file schema feature — no need to embed them here.
 *
 * Usage:
 *   npx tsx scripts/generate-schema.ts mysql
 *   npx tsx scripts/generate-schema.ts postgresql
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SCHEMA_PATH = resolve(ROOT, 'prisma', 'schema.prisma');

interface DialectConfig {
  provider: string;
  envVar: string;
}

const dialects: Record<string, DialectConfig> = {
  mysql: { provider: 'mysql', envVar: 'MYSQL_URL' },
  postgresql: { provider: 'postgresql', envVar: 'POSTGRES_URL' },
};

const dialect = process.argv[2];
if (!dialect || !(dialect in dialects)) {
  console.error(`Usage: tsx scripts/generate-schema.ts <${Object.keys(dialects).join('|')}>`);
  process.exit(1);
}

const config = dialects[dialect]!;
const schema = `// Auto-generated by scripts/generate-schema.ts for ${dialect}.
// Models are defined in prisma/models.prisma (combined via multi-file schema).

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${config.provider}"
  url      = env("${config.envVar}")
}
`;

writeFileSync(SCHEMA_PATH, schema, 'utf-8');
console.log(`Generated prisma/schema.prisma for ${dialect}`);
